config/routes.rb
Rails.application.routes.draw do
  root 'bar#index'

  get '/login' => 'session#index', as: 'login'

  get '/sign_up' => 'session#new'

  post '/sign_up' => 'session#create'

  post 'session/authorise'

  get 'session/destroy'

  post 'session/update'

  get 'session/forgot_password'

  resources :beverages

  resources :pumps

  resources :cocktails

  resources :bar

  post '/cocktails/order/:id' => 'cocktails#order', as: 'order_cocktail'

  get '/admin' => 'admin#index', as: 'admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/beverage.rb
class Beverage < ApplicationRecord
  belongs_to :pump
  validates :name, presence: true, allow_blank: false
  validates :pump_id, presence: true, allow_blank: false
end

app/controllers/beverages_controller.rb
class BeveragesController < ApplicationController
  def index
    @beverages = Beverage.all
  end

  def new
    @beverage = Beverage.new
    @available_pumps = available_pumps
    @available_pumps.compact!
  end

  def create
    @beverage = Beverage.new(beverage_params)
    if @beverage.save
      flash[:success] = "<span class='ti-check'></span> Beverage '#{@beverage.name}' successfully added and registered on port #{@beverage.pump.port}"
      redirect_to beverages_url
    else
      @available_pumps = available_pumps
      @available_pumps.compact!
      render action: 'new'
    end
  end

  def update
    @beverage = Beverage.find(params[:id])
    @beverage.name = beverage_params[:name]
    @beverage.description = beverage_params[:description]
    @beverage.pump_id = beverage_params[:pump_id]
    if @beverage.save
      flash[:success] = "<span class='ti-check'></span> Beverage '#{@beverage.name}' successfully updated and registered on port #{@beverage.pump.port}"
      redirect_to beverages_url
    else
      @available_pumps = available_pumps
      @available_pumps.push([@beverage.pump.port, @beverage.pump.id])
      @available_pumps.compact!
      render action: 'edit'
    end
  end

  def edit
    @beverage = Beverage.find(params[:id])
    @available_pumps = available_pumps
    @available_pumps.push([@beverage.pump.port, @beverage.pump.id])
    @available_pumps.compact!
  end

  def destroy
    @beverage = Beverage.find(params[:id])
    if @beverage.destroy
      flash[:success] = "<span class='ti-check'></span> Beverage '#{@beverage.name}' successfully removed"
    end
    redirect_to beverages_url
  end

  private

  def beverage_params
    params.require(:beverage).permit(:name, :description, :pump_id)
  end
end

app/helpers/beverage_helper.rb
module BeverageHelper
end

app/views/beverages/_list.html.erb
<div class="col-md-12 col-md-push-2">
  <% if @beverages && !@beverages.empty? %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Pump Port</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% for beverage in @beverages %>
          <tr>
            <td><%= beverage.name %>
            <td><%= beverage.pump.port %></td>
            <td class='button-wrapper'>
              <%= link_to edit_beverage_url(beverage), class: 'btn btn-primary fh5co-btn-icon' do %>
                <i class="ti-pencil"></i> Edit
              <% end %>
              <%= link_to beverage_url(beverage), class: 'btn btn-primary fh5co-btn-icon', method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i class="ti-close"></i> Remove
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p> You have no beverages yet. Follow the link on the top tab to add a new beverage and link to a pump</p>
  <% end %>
</div>

app/views/beverages/_tabs.html.erb
<div class="col-md-12 col-md-push-2">
  <ul class="nav nav-tabs">
    <li<%= active_tab(ctrler: 'beverages', action: 'index') %>>
      <%= link_to beverages_url do %>
        <i class="ti-pencil"></i> Manage
      <% end %>
    </li>
    <li<%= active_tab(ctrler: 'beverages', action: 'new') ||  active_tab(ctrler: 'beverages', action: 'create')%>>
      <%= link_to new_beverage_url do %>
        <i class="ti-plus"></i> Add
      <% end %>
    </li>
  </ul>
</div>

app/views/beverages/edit.html.erb
<div class="col-md-12 col-md-push-2">
  <%= form_for @beverage, method: :put do |f| %>
    <% if @beverage.errors.any? %>
    <div id="error_explanation" class='col-md-7 alert alert-danger'>
      <p><%= pluralize(@beverage.errors.count, "error") %> prohibited your beverage from being updated:</p>
      <ul>
        <% @beverage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="col-md-7">
      <div class="form-group">
        <%= f.label :name, class: 'sr-only' %>
        <%= f.text_field :name, class: 'form-control input-lg', placeholder: 'Beverage Name' %>
      </div>
    </div>
    <div class="col-md-7">
      <div class="form-group">
        <%= f.label :description, class: 'sr-only' %>
        <%= f.text_area :description, class: 'form-control input-lg', placeholder: 'Enter a description of this beverage' %>
      </div>
    </div>
    <div class="col-md-7">
      <div class="form-group">
        <%= f.label :pump, class: 'sr-only' %>
        <%= f.select :pump_id, options_for_select(@available_pumps, @beverage.pump_id), {:include_blank => false}, { class: 'form-control input-lg' } %>
      </div>
    </div>
    <div class="col-md-7">
      <%= f.submit "Update Beverage", class: 'btn btn-primary btn-md' %>
    </div>
  <% end %>
</div>

app/views/beverages/index.html.erb
<%= render 'list' %>

app/views/beverages/new.html.erb
<div class="col-md-12 col-md-push-2">
  <%= form_for @beverage, url: {action: "create"} do |f| %>
    <% if @beverage.errors.any? %>
    <div id="error_explanation" class='col-md-7 alert alert-danger'>
      <p><%= pluralize(@beverage.errors.count, "error") %> prohibited your beverage from being created:</p>

      <ul>
        <% @beverage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="col-md-7">
      <div class="form-group">
        <%= f.label :name, class: 'sr-only' %>
        <%= f.text_field :name, class: 'form-control input-lg', placeholder: 'Beverage Name' %>
      </div>
    </div>
    <div class="col-md-7">
      <div class="form-group">
        <%= f.label :description, class: 'sr-only' %>
        <%= f.text_area :description, class: 'form-control input-lg', placeholder: 'Enter a description of this beverage' %>
      </div>
    </div>
    <div class="col-md-7">
      <div class="form-group">
        <%= f.label :pump, class: 'sr-only' %>
        <%= f.select :pump_id, options_for_select(@available_pumps), {:include_blank => "Select Pump"}, { class: 'form-control input-lg' } %>
      </div>
    </div>
    <div class="col-md-7">
      <%= f.submit "Create Beverage", class: 'btn btn-primary btn-md' %>
    </div>
  <% end %>
</div>