config/routes.rb
Rails.application.routes.draw do
  root 'bar#index'

  get '/login' => 'session#index', as: 'login'

  get '/sign_up' => 'session#new'

  post '/sign_up' => 'session#create'

  post 'session/authorise'

  get 'session/destroy'

  post 'session/update'

  get 'session/forgot_password'

  resources :beverages

  resources :pumps

  resources :cocktails

  resources :bar

  post '/cocktails/order/:id' => 'cocktails#order', as: 'order_cocktail'

  get '/admin' => 'admin#index', as: 'admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :ingredients, :dependent => :destroy, inverse_of: :cocktail
  has_many :images, :dependent => :destroy, inverse_of: :cocktail
  validates :name, :price, :presence => true
  accepts_nested_attributes_for :ingredients, :allow_destroy => true, :reject_if => proc { |d| d['beverage_id'].blank? }
  accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if => proc { |d|
    d.empty? || d['uploaded_file'].class != ActionDispatch::Http::UploadedFile
  }
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def list
  end

  def new
    @cocktail = Cocktail.new
    5.times do
      @cocktail.images.build
      @cocktail.ingredients.build
    end
    @beverages = available_beverages
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      flash[:success] = "<span class='ti-check'></span> Cocktail '#{@cocktail.name}' successfully added"
      redirect_to cocktails_url
    else
      @beverages = available_beverages
      render action: 'new'
    end
  end

  def destroy
    cocktail = Cocktail.find(params[:id])
    if cocktail.destroy
      flash[:success] = "<span class='ti-check'></span> Cocktail '#{cocktail.name}' successfully deleted"
    end
    redirect_to cocktails_url
  end

  def order

  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :price, images_attributes:[:uploaded_file], ingredients_attributes:[:beverage_id, :measurement])
  end
end

app/helpers/cocktail_helper.rb
module CocktailHelper
end

app/views/cocktails/_ingredient_fields.html.erb
<div class="col-md-7">
  <div class="form-group">
    <%= f.label :beverage_id, class: 'sr-only' %>
    <%= f.select :beverage_id, options_for_select(@beverages), {:include_blank => "Select Beverage"}, {class: 'form-control input-lg'} %>
  </div>
</div>
<div class="col-md-2">
  <p> X </p>
</div>
<div class="col-md-3">
  <div class="form-group">
    <%= f.label :measurement, nil, class: 'sr-only' %>
    <%= f.text_field :measurement, class: 'form-control input-lg' , placeholder: 'ML'%>
  </div>
</div>

app/views/cocktails/_list.html.erb
<!-- Start Work -->
<div id="fh5co-work">
  <div class="container">
    <div class="row">
      <% if @cocktails && !@cocktails.empty? %>
        <% for cocktail in @cocktails %>
          <div class="col-md-4 col-sm-4 col-xs-4 fh5co-work-wrap">
            <div href="#" class="fh5co-work-item js-fh5co-work-item">
              <% if cocktail.images.empty? %>
                <img src="/assets/work_1.jpg" alt="Image" class="img-responsive">
              <% else %>
                <img src="<%= cocktail.images.first.file_path %>" alt="Image" class="img-responsive">
              <% end %>
              <div class="fh5co-overlay-bg js-fh5co-overlay-bg"></div>
              <div class="fh5co-overlay-text js-fh5co-overlay-text">
                <h1>£<%= cocktail.price %></h1>
                <h2><%= cocktail.name %></h2>
                <ul class="fh5co-categories">
                  <% for ingredient in cocktail.ingredients %>
                    <li><%= ingredient.measurement %>ml X <%= ingredient.beverage.name %></li>
                  <% end %>
                </ul>
                <%= link_to order_cocktail_path(cocktail), method: :post, class: 'btn btn-primary fh5co-btn-icon' do %>
                  <i class="ti-shopping-cart"></i>
                <% end %>
                <%= link_to cocktail_path(cocktail), class: 'btn btn-primary fh5co-btn-icon' do %>
                  <i class="ti-eye"></i>
                <% end %>
                <%= link_to edit_cocktail_path(cocktail), class: 'btn btn-primary fh5co-btn-icon' do %>
                  <i class="ti-pencil"></i>
                <% end %>
                <%= link_to cocktail_url(cocktail), class: 'btn btn-primary fh5co-btn-icon', method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <i class="ti-close"></i>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <!-- Start More Works -->
      <div class="row">
        <div class="col-md-12 text-center">
        <a href="#" class="fh5co-view js-fh5co-view"><span class="fh5co-icon-view"><i class="ti-plus"></i></span> <span class="js-fh5co-view-text">View All</span></a>
        </div>
      </div>
      <!-- End More Works -->
    <% else %>
      <p class='col-md-12 col-md-push-2'> There has been no cocktails added yet. Please add some</p>
    <% end %>

  </div>
</div>
<!-- End Work -->

app/views/cocktails/_tabs.html.erb
<div class="col-md-12 col-md-push-2">
  <ul class="nav nav-tabs">
    <li<%= active_tab(ctrler: 'cocktails', action: 'index') %>>
      <%= link_to cocktails_url do %>
        <i class="ti-pencil"></i> Manage
      <% end %>
    </li>
    <li<%= active_tab(ctrler: 'cocktails', action: 'new') ||  active_tab(ctrler: 'cocktails', action: 'create')%>>
      <%= link_to new_cocktail_url do %>
        <i class="ti-plus"></i> Add
      <% end %>
    </li>
  </ul>
</div>

app/views/cocktails/index.html.erb
<%= render 'list' %>

app/views/cocktails/new.html.erb
<div class="col-md-12 col-md-push-2">
  <%= form_for @cocktail, url: {action: "create"}, :multipart => true do |f| %>
  <% if @cocktail.errors.any? %>
  <div id="error_explanation" class='col-md-7 alert alert-danger'>
    <p><%= pluralize(@cocktail.errors.count, "error") %> prohibited your cocktail from being created:</p>

    <ul>
      <% @cocktail.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="col-md-7">
    <div class="form-group">
      <%= f.label :name, class: 'sr-only' %>
      <%= f.text_field :name, class: 'form-control input-lg', placeholder: 'Cocktail Name' %>
    </div>
  </div>
  <div class="col-md-7">
    <div class="form-group">
      <%= f.label :description, class: 'sr-only' %>
      <%= f.text_area :description, class: 'form-control input-lg', placeholder: 'Enter a description of this cocktail' %>
    </div>
  </div>
  <div class="col-md-7">
    <div class="form-group">
      <%= f.label :price, class: 'sr-only' %>
      <%= f.text_field :price, class: 'form-control input-lg', placeholder: 'Cocktail Price' %>
    </div>
  </div>
  <div class="col-md-7">
    <%= f.fields_for :images do |f| %>
      <div class="form-group">
        <%= f.label :uploaded_file, nil, class: 'sr-only' %>
        <%= f.file_field :uploaded_file, class: 'form-control input-lg' %>
      </div>
    <% end %>
  </div>
  <div class="col-md-7">
    <%= f.fields_for :ingredients do |builder| %>
      <% if builder.object.new_record? %>
        <%= render 'ingredient_fields', :f => builder, :no_js => true %>
      <% end %>
    <% end %>
  </div>
  <div class="col-md-7">
    <%= f.submit "Create Cocktail", class: 'btn btn-primary btn-md' %>
  </div>
  <% end %>
  <div class="fh5co-spacer fh5co-spacer-xs"></div>
</div>