config/routes.rb
Rails.application.routes.draw do
  root 'bar#index'

  get '/login' => 'session#index', as: 'login'

  get '/sign_up' => 'session#new'

  post '/sign_up' => 'session#create'

  post 'session/authorise'

  get 'session/destroy'

  post 'session/update'

  get 'session/forgot_password'

  resources :beverages

  resources :pumps

  resources :cocktails

  resources :bar

  post '/cocktails/order/:id' => 'cocktails#order', as: 'order_cocktail'

  get '/admin' => 'admin#index', as: 'admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :require_login

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = '<span class="ti-check"></span> Account Successfully Registered. Enjoy the bar!'
      redirect_to root_url
    else
      render :new
    end
  end

  def authorise
    user = User.find_by_email(params[:user][:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:user][:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
      flash[:danger] = '<span class="ti-alert"></span> We do not recognise those details. Please try again.'
      redirect_to login_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url
  end

  def update
  end

  def forgot_password
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/_sign_in_or_sign_up_nav.html.erb
<!-- Main Nav -->
<div id="fh5co-main-nav">
  <nav id="fh5co-nav" role="navigation">
    <ul>
      <li>
        <% if current_page?(action: 'new') %>
          <%= link_to 'Sign In', login_path %>
        <% else %>
          <%= link_to 'Register/Sign Up', sign_up_path %>
        <% end %>
      </li>
    </ul>
  </nav>
</div>
<!-- Main Nav -->

app/views/session/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2 class="fh5co-uppercase-heading-sm text-center">Sign in</h2>
      <div class="fh5co-spacer fh5co-spacer-xs"></div>
    </div>
    <div class="col-md-7 col-md-offset-4">
      <%= form_for :user, url: {action: "authorise"} do |f| %>
        <div class="col-md-7">
          <div class="form-group">
            <%= f.label :email, class: 'sr-only' %>
            <%= f.text_field :email, class: 'form-control input-lg', placeholder: 'Email' %>
          </div>
        </div>
        <div class="col-md-7">
          <div class="form-group">
            <%= f.label :password, class: 'sr-only' %>
            <%= f.password_field :password, class: 'form-control input-lg', placeholder: 'Password' %>
          </div>
        </div>
        <div class="col-md-7">
          <div class="form-group">
            <%= f.submit "Sign In", class: 'btn btn-primary btn-md' %>
            <%= link_to 'Forgot?', session_forgot_password_path, class: 'btn btn-outline btn-md' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/session/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2 class="fh5co-uppercase-heading-sm text-center">Sign Up</h2>
      <div class="fh5co-spacer fh5co-spacer-xs"></div>
    </div>
    <div class="col-md-7 col-md-offset-4">
      <%= form_for @user, url: {action: "create"} do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation" class='col-md-7 alert alert-danger'>
            <p><%= pluralize(@user.errors.count, "error") %> prohibited your account from being registered:</p>

            <ul>
              <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="col-md-7">
          <div class="form-group">
            <%= f.label :name, class: 'sr-only' %>
            <%= f.text_field :name, class: 'form-control input-lg', placeholder: 'Full Name' %>
          </div>
        </div>
        <div class="col-md-7">
          <div class="form-group">
            <%= f.label :email, class: 'sr-only' %>
            <%= f.text_field :email, class: 'form-control input-lg', placeholder: 'Email' %>
          </div>
        </div>
        <div class="col-md-7">
          <div class="form-group">
            <%= f.label :password, class: 'sr-only' %>
            <%= f.password_field :password, class: 'form-control input-lg', placeholder: 'Password'%>
          </div>
        </div>
        <div class="col-md-7">
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'sr-only' %>
            <%= f.password_field :password_confirmation, class: 'form-control input-lg', placeholder: 'Confirm Password'%>
          </div>
        </div>
        <div class="col-md-7">
          <%= f.submit "Register", class: 'btn btn-primary btn-md' %>
        </div>
      <% end %>
    </div>
  </div>
</div>