config/routes.rb
Rails.application.routes.draw do
  root 'bar#index'

  get '/login' => 'session#index', as: 'login'

  get '/sign_up' => 'session#new'

  post '/sign_up' => 'session#create'

  post 'session/authorise'

  get 'session/destroy'

  post 'session/update'

  get 'session/forgot_password'

  resources :beverages

  resources :pumps

  resources :cocktails

  resources :bar

  post '/cocktails/order/:id' => 'cocktails#order', as: 'order_cocktail'

  get '/admin' => 'admin#index', as: 'admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beverage.rb
class Beverage < ApplicationRecord
  belongs_to :pump
  validates :name, presence: true, allow_blank: false
  validates :pump_id, presence: true, allow_blank: false
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :ingredients, :dependent => :destroy, inverse_of: :cocktail
  has_many :images, :dependent => :destroy, inverse_of: :cocktail
  validates :name, :price, :presence => true
  accepts_nested_attributes_for :ingredients, :allow_destroy => true, :reject_if => proc { |d| d['beverage_id'].blank? }
  accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if => proc { |d|
    d.empty? || d['uploaded_file'].class != ActionDispatch::Http::UploadedFile
  }
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :cocktail, inverse_of: :images

  def uploaded_file=(incoming_file)
    self.content_type = incoming_file.content_type
    FileUtils.mkdir_p(upload_dir)
    filename = "upload_#{SecureRandom.uuid}"
    write_path = File.join(upload_dir, filename)
    read_path = File.join(file_read_path, filename)
    File.open(write_path, "wb") { |f| f.write(incoming_file.read) }
    self.file_path = read_path
  end

  def filename=(new_filename)
    write_attribute("filename", sanitize_filename(new_filename))
  end

  private

  def upload_dir
    'public/images/upload'
  end

  def file_read_path
    '/images/upload'
  end

  def content_format
    if !["image/jpg", "image/jpeg", "image/gif", "image/tif", "image/png"].include?(self.content_type.downcase)
      errors.add("Attachment Format", "should be one of the following: GIF, TIF, JPG, JPEG or PNG")
      return false
    else
      return true
    end
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :cocktail, inverse_of: :ingredients
  belongs_to :beverage
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :cocktail
end

app/models/pump.rb
class Pump < ApplicationRecord
  has_many :beverages
  validates :port, numericality: { only_integer: true }
  validates :port, presence: true, allow_blank: false
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :beverage
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :orders
  validates :name, presence: true
  validates :email, presence: true
  validates_format_of :email, :with => /.+@.+\..+/i
  PASSWORD_FORMAT = /\A
  (?=.{8,})          # Must contain 8 or more characters
  (?=.*\d)           # Must contain a digit
  (?=.*[a-z])        # Must contain a lower case character
  (?=.*[A-Z])        # Must contain an upper case character
/x
  validates :password, length: { within: 8..40 }, format: { with: PASSWORD_FORMAT, message: "Must contain a digit, lower and upper case character" }, on: :create
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/bar_controller.rb
class BarController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def add_to_basket
  end
end

app/controllers/pumps_controller.rb
class PumpsController < ApplicationController
  def index
    @pumps = Pump.all
  end

  def new
    @pump = Pump.new
  end

  def create
    @pump = Pump.new(pump_params)
    if @pump.save
      flash[:success] = "<span class='ti-check'></span> GPIO Port '#{@pump.port}' successfully registered"
      redirect_to pumps_url
    else
      render action: 'new'
    end
  end

  def update
    @pump = Pump.find(params[:id])
    @pump.port = pump_params[:port]
    if @pump.save
      flash[:success] = "<span class='ti-check'></span> GPIO Port '#{@pump.port}' successfully updated"
      redirect_to pumps_url
    else
      render action: 'edit'
    end
  end

  def edit
    @pump = Pump.find(params[:id])
  end

  private

  def pump_params
    params.require(:pump).permit(:port)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :require_login

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = '<span class="ti-check"></span> Account Successfully Registered. Enjoy the bar!'
      redirect_to root_url
    else
      render :new
    end
  end

  def authorise
    user = User.find_by_email(params[:user][:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:user][:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
      flash[:danger] = '<span class="ti-alert"></span> We do not recognise those details. Please try again.'
      redirect_to login_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url
  end

  def update
  end

  def forgot_password
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_active_link(url: nil, ctrler: nil)
    ' class=fh5co-active' if url && current_page?(url) || ctrler && controller.controller_name == ctrler.to_s
  end

  def active_tab(ctrler:, action:)
    ' class=active' if controller.controller_name == ctrler.to_s && params[:action] == action
  end

  def render_sub_tabs
    case controller.controller_name
    when 'pumps'
      render 'pumps/tabs'
    when 'beverages'
      render 'beverages/tabs'
    when 'cocktails'
      render 'cocktails/tabs'
    end
  end
end

app/helpers/bar_helper.rb
module BarHelper
end

app/helpers/beverage_helper.rb
module BeverageHelper
end

app/helpers/cocktail_helper.rb
module CocktailHelper
end

app/helpers/pump_helper.rb
module PumpHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/layouts/_signed_in_nav.html.erb
<div id="fh5co-main-nav">
  <nav id="fh5co-nav" role="navigation">
    <ul>
      <li<%= set_active_link(url: root_url) %>>
        <%= link_to 'Bar', root_url %>
      </li>
      <li<%= set_active_link(ctrler: :pumps) %>>
        <%= link_to 'Pumps', pumps_url %>
      </li>
      <li<%= set_active_link(ctrler: :beverages) %>>
        <%= link_to 'Beverages', beverages_url %>
      </li>
      <li<%= set_active_link(ctrler: :cocktails) %>>
        <%= link_to 'Cocktails', cocktails_url %>
      </li>
      <li<%= set_active_link(ctrler: :admin) %>>
        <%= link_to 'Admin', admin_url %>
      </li>
    </ul>
    <%= link_to 'Logout', session_destroy_url, class: 'fh5co-nav-call-to-action js-fh5co-nav-call-to-action' %>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Robo: Bar-Mix-R</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Automated mixologist" />
    <meta name="keywords" content="automated bartender, robo mixologist, mixology, bartender, raspberry pi, peristaltic pump" />
    <meta name="author" content="voke.anighoro@gmail.com" />

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
  <link rel="shortcut icon" href="/assets/favicon.ico">

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>

    <!-- Header -->
    <header id="fh5co-header" role="banner">
      <div class="container">
        <!-- Logo -->
        <div id="fh5co-logo">
          <a href="index.html">
            <img src="/assets/logo.png" alt="Work Logo">
          </a>

        </div>
        <!-- Logo -->

        <!-- Mobile Toggle Menu Button -->
        <a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle"><i></i></a>

        <!-- Main Nav -->
        <% if current_user %>
          <%= render 'layouts/signed_in_nav' %>
        <% else %>
          <%= render 'session/sign_in_or_sign_up_nav' %>
        <% end %>
        <!-- Main Nav -->
      </div>
    </header>
    <!-- Header -->

    <main role="main">
      <div class='container'>
        <div class='row'>
          <div class="col-md-push-3 col-md-7">
            <% flash.each do |key, value| %>
              <div class="alert alert-<%= key %>"><%= value.html_safe %></div>
            <% end %>
          </div>
        </div>
      </div>
      <%= render_sub_tabs %>
      <div class="fh5co-spacer fh5co-spacer-sm"></div>
      <%= yield %>
      <div class="fh5co-spacer fh5co-spacer-sm"></div>
    </main>

    <footer id="fh5co-footer" role="contentinfo">
      <div class="container">
        <div class="row">
          <div class="col-md-push-4 col-md-6">
            <p class="fh5co-copyright">
              <small>(c) 2016 <a href="/">Bar-Mix-R</a>. All Rights Reserved. <br>
Designed by: <a href="http://www.vtechnologiesltd.com/">vTechnologies Ltd</a></small>
            </p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Go To Top -->
    <a href="#" class="fh5co-gotop"><i class="ti-shift-left"></i></a>


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </body>
</html>